---
version: "3.8"

services:
  twtxt:
    image: prologic/twtxt:latest
    command: -d /data -s bitcask:///data/twtxt.db -u https://twtxt.net
    environment:
      - OPEN_PROFILES=true
      - OPEN_REGISTRATIONS=true
      - COOKIE_SECRET=supersecretchangeme
    volumes:
      - twtxt:/data
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == dm4.mills.io"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.twtxt_twtxt.loadbalancer.server.port=8000"
        - "traefik.http.routers.twtxt_twtxt.rule=Host(`twtxt.net`)"
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true

volumes:
  twtxt:
    driver: local
